Todo/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("login.urls")),
    path("to/",include("Todos.urls"))
]

Todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path("",views.liste,name = "list-todos"),
    path("create/", views.create_todo, name = "create-todos"),
    path("<int:pk>/delete/",views.delete_todo,name = "delete-todos"),
    path("<int:pk>/update/",views.update_todo,name = "update-todos"),
    path("send-mail/",views.send_all_email,name = "email"),
]

Todos/models.py
from django.db import models
from Todo import settings
# Create your models here.
class Todos(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    infos = models.TextField(max_length = 200)
    def __str__(self):
        return self.title 

Todos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from . import models
from login import models as lg 
from Todo import settings

from django.core.mail import EmailMessage, EmailMultiAlternatives

# Create your views here.
#  display all user's todo
def liste(request):
    all_list_raw = models.Todos.objects.filter(user = request.user.pk) 
    return render(request,"Todos/list.html",{"all_list":all_list_raw,"user":request.user.pk})

# allow a user to create a new todo  
def create_todo(request):
    if request.POST:
        user = request.user
        title = request.POST.get("title") 
        infos = request.POST.get("infos")
        print(f"user is {user}\ntitle is {title}\ninfos are {infos} ")
        post = models.Todos(user = user,title = title, infos = infos)
        post.save()
    return render(request,"Todos/create.html")

#allow the user to delete a todo
def delete_todo(request,pk):
    post = models.Todos.objects.get(pk=pk).delete()
    return HttpResponseRedirect(reverse('todos:list-todos'))

def update_todo(request,pk):
    post = models.Todos.objects.get(pk=pk)
    # if the user send a post request after modifing the todo
    if request.POST : 
        title = request.POST.get("Title")
        infos = request.POST.get('info')
        post.title = title
        post.infos = infos
        post.save()
        return HttpResponseRedirect(reverse("todos:list-todos"))
    # display the "form" for updating the todo
    else : 
        return render(request,'Todos/update.html',{"post":post}) 

#test pour envoyer des emails généralisé
def send_all_email(request):
    queryset = lg.MyUser.objects.all() #on prend tous les emails présent dans la base de données 
    to = []
    for mail in queryset : 
        to.append(mail)
    # on s'attend à recevoir un post request pour envoyer les emails à tous le monde 
    if request.POST :
        # on choppe le sujet et le texte de l'email à envoyer
        subject = request.POST.get("subject")
        email = request.POST.get("email")  
        from_email = settings.EMAIL_HOST_USER
        msg = EmailMultiAlternatives(subject, '', from_email, to)
        msg.attach_alternative(email, "text/html")
        msg.send()
        return HttpResponse("On a envoyé l'email à tous les membres de la base de données ")
    return render(request,"general_email.html")

templates/Todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>création de post selon l'utilisateur (si tous se passe bien)</h1>
    {% if user.is_authenticated %}
    <form  method="POST">
        {% csrf_token %}
        <label for="title">title</label>
        <input type="text" name="title" placeholder="Enter Email">

        <label for="infos">infos</label>
        <input type="textarea" name="infos" id="">
        <input type="submit" value="enregistrer" name="Login">
    </form>
    {% else %}
        <h1>Please login </h1>
    {% endif %}
</body>
</html>

templates/Todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Page qui va afficher tous les todos </h1>
    <h2>Welcome @{{request.user.username}}</h2>
    {% for list in all_list %}
        {% if list.user == request.user %}
            
            {{list.title}}
            pk = {{list.pk}}
            <br>
            {{list.infos}} <a href="{% url 'todos:update-todos' pk=list.pk%}">mettre à jour </a> | <a href="{% url 'todos:delete-todos' pk=list.pk%}">supprimer</a>
            <br>
            {{list.user}} 
            <br>
            <p></p>
        {% endif %}
    {% endfor %}
</body>
</html>

templates/Todos/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Page pour modifier un todo  </h1>
    <h2>Welcome @{{request.user.username}}</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <label for="Title">
            Title
        </label>
        <input type="text" name="Title" id="" value="{{post.title}}">
        <label for="info">
            infos
        </label>
        <input type="text" name="info" id="" value="{{ post.infos}}">
        <input type="submit" name="" id="" value="envoyer">
    </form>
</body>
</html>