Todo/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("login.urls")),
    path("to/",include("Todos.urls"))
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('',views.home,name = 'home'),
    path('login/', views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = "logout"),
    path("register/",views.user_register,name = "register"),
    path('activate/<slug:uidb64>/<slug:token>/',views.activate_account,name = 'activate'),
    path("change_password/",views.update_password, name = "change_password"),
    path("changed_password/",views.changed_password, name = "changed_password"),
    path("reset_password/",views.email_reset_password, name = "email_reset_password"),#on met le lien pour recevoir un mail
    path("reset_password/activation/<slug:uidb64>/<slug:token>/",views.reset_password,name = "reset_password"),
    
]

login/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length = 60)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

login/forms.py
from .models import MyUser
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm 

class CustomUserCreationForm(UserCreationForm):
    #think I neek to add extrafields here and the main parts go into the Meta
    password1 = forms.CharField(widget = forms.PasswordInput())
    password2 = forms.CharField(widget = forms.PasswordInput())
    class Meta(UserCreationForm):
        model = MyUser
        fields = ('email','username','password1','password2')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = MyUser
        fields = ('email',)
    
class CustomUserChangePassword(PasswordChangeForm):
    old_password = forms.CharField(widget = forms.PasswordInput())
    new_password1 = forms.CharField(widget = forms.PasswordInput())
    new_password2 = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = MyUser
        fields = ('old_password','new_password1','new_password2') 
    

login/views.py
from django.shortcuts import render 
from django.contrib import messages

#pour envoyer des mails : 
from django.contrib.sites.shortcuts import get_current_site 
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template # charger une page html
from Todo import settings
#permet de gérer tout ce qui est en rapport avec la connexion/déconnexion de l'utilisateur
from django.contrib.auth import authenticate, login, logout,update_session_auth_hash
#affichage de page selon la situation 
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse 

from django.template.loader import render_to_string #convertit une page html en mail pour envoyer le lien d'activation 
#création d'outil pour créer/décoder des ine time link
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token

#formulaire pour que les gens puissent s'enregistrer
from .forms import CustomUserCreationForm, CustomUserChangePassword

#import du modèle d'utilisateur que l'on a créé
from .models import MyUser


from django.contrib.auth.decorators import login_required


#home page
def home(request):
    return render(request,'home.html')
#login page
def user_login(request):
    if request.POST :
        email = request.POST.get("email") 
        password = request.POST.get("password")
        user = authenticate(email = email, password = password)
        #check if the user exists and if it's account is active
        if user is not None and user.is_active :
            login(request,user)
            return HttpResponseRedirect(reverse('login:home'))
        return render(request,'login/login.html')
    return render(request,'login/login.html')

#logout page
def user_logout(request):
    logout(request) 
    return HttpResponseRedirect(reverse('login:home'))

#register page
def user_register(request):
    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        #partie pour l'envoie d'un email d'activation 
        # current_site = get_current_site(request)
        # email_subject = 'Activation de votre compte'
        # message = render_to_string('login/activate_account.html',
        #         {'user':user,'domain':current_site,
        #         'uid':urlsafe_base64_encode(force_bytes(user.pk)),
        #         'token': account_activation_token.make_token(user),})

        # to_email = form.cleaned_data.get('email')
        # email = EmailMessage(email_subject,message,to =[to_email])
        # email.send()
        subject, from_email, to = 'Activation de votre compte', settings.EMAIL_HOST_USER, form.cleaned_data.get('email')
        text_content = ''
        # = render_to_string("login/activate_account.html")#'<p>This is an <strong>important</strong> message.</p>'
        html_content = f"Hi {user.username}\nPlease click on the link to confirm your registration http://{get_current_site(request)}/{account_activation_token.make_token(user)}\n<p  style='color: blue;' >Test couleur bleue</p>"
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return HttpResponse("On vous a envoyé un email, cliquez sur le lien pour terminer votre inscription ")
    else :
        form = CustomUserCreationForm()
    return render(request,'login/register.html',{'form':form})

#activate account
def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')
    
#change password
@login_required
def update_password(request):
    if request.method =='POST':
        form = CustomUserChangePassword(request.user,request.POST)
        if form.is_valid() :
            user = form.save()
            update_session_auth_hash(request,user)
            messages.success(request,'Your password was successfully updated !')
            return HttpResponseRedirect(reverse('login:changed_password'))
        else :
            messages.error(request,'Please correct the error below.')
    else :
        form = CustomUserChangePassword(request.user)
    return render(request,'login/change_password.html',{'form':form})

#temp page to say that the password has been changed
def changed_password(request):
    return render(request,'login/changed.html')

#reset a forgotten password
def email_reset_password(request):
    if request.POST:
        email = request.POST.get("email")
        #on vérifie qu'un compte avec cette adresse mail existe
        try :
            user = MyUser.objects.get(email=email)
        except:
            return HttpResponse("Compte n'existe pas") 
        current_site = get_current_site(request)
        email_subject = 'Réinitilisation de votre mot de passe '
        message = render_to_string('login/reset_password_real.html',
                {'user':user,'domain':current_site,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),})
        to_email = email
        email = EmailMessage(email_subject,message,to =[to_email])
        email.send()
        return HttpResponse("On vous a envoyé un email, cliquez sur le lien pour terminer votre inscription ")
    return render(request,"login/reset_password.html")

#activate account
def reset_password(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        if request.POST:
            password1 = request.POST.get("password1")
            password2 = request.POST.get("password2")
            if password1 == password2:
                user.set_password(password2)
                user.save()
            return HttpResponse('Your account has been activate successfully')
        else :
            return render(request,'login/reset_slug_password.html')
    else:
        return HttpResponse('Activation link is invalid!')

templates/login/activate_account.htm
{% autoescape off %}
Hi {{ user.username }},
Please click on the link [depuis template, dans le sous dossier login] to confirm your registration,
http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/login/activate_account.html
<!DOCTYPE html>
<head>
</head>
<body>
    {% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
<div style="color: blue;">Test</div>
http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}

<h1>Partie avec le test de la couleur </h1>
Hi {{ user.username }},
Please click on the link [depuis template, dans le sous dossier login] to confirm your registration,
<p  style="color: blue;">Test couleur bleue</p>
http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}
{% endautoescape %}
</body>
</html>
 

templates/login/change_password.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>

templates/login/changed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>changed password</title>
</head>
<body>
    <h1>votre mot de passe a été changé </h1>
    <a href="{% url 'login:home' %}"> home </a>
</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <h1>Login page</h1>
    {% if user.is_authenticated %}
        <h1>{{user.username}}</h1>
    <a href="{% url 'logout' %}">logout</a>
    {% else %}
    <form  method="POST">
        {% csrf_token %}
        <label for="email">email</label>
        <input type="text" name="email" placeholder="Enter Email">

        <label for="password">Password</label>
        <input type="Password" name="password" id="">
        <input type="submit" value="Login" name="Login">
    </form>
    {% endif %}
</body>
</html>

templates/login/not_active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Not active</title>
</head>
<body>
    <h1>compte pas actif </h1>
</body>
</html>

templates/login/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <h1 style="color: blue;">Register page</h1>
    <form  method="POST">
        {% csrf_token %}
        email : {{ form.email}}
        <br>
        username {{ form.username }}
        <br>
        password 1 :{{ form.password1 }}
        <br>
        password : {{ form.password2 }}
        <br>
        <input type="submit" name="" value="Envoyer" id="">
    </form>

</html>

templates/login/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset page</title>
</head>
<body>
    <h1>reset password page</h1>
    <form  method="POST">
        {% csrf_token %}
        <label for="email">email</label>
        <input type="text" name="email" placeholder="Enter Email">
        <input type="submit" value="Login" name="Reset mot de passe ">
    </form>
</body>
</html>

templates/login/reset_password_real.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link  to reset your password,
http://{{ domain }}{% url 'login:reset_password' uidb64=uid token=token %}
{% endautoescape %}

templates/login/reset_slug_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset slug page</title>
</head>
<body>
    <h1>reset slug file page</h1>
    <form  method="POST">
        {% csrf_token %}
        <label for="password 1">Password</label>
        <input type="password" name="password1" placeholder="">
        <label for="password2">Password</label>
        <input type="Password" name="password2" id="">
        <input type="submit" value="Login" name="Login">
    </form>
</body>
</html>