Todo/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("login.urls")),
    path("to/",include("Todos.urls"))
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('',views.home,name = 'home'),
    path('login/', views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = "logout"),
    path("register/",views.user_register,name = "register"),
    path('activate/<slug:uidb64>/<slug:token>/',views.activate_account,name = 'activate'),
    path("change_password/",views.update_password, name = "change_password"),
    path("changed_password/",views.changed_password, name = "changed_password"),
    path("reset_password/",views.email_reset_password, name = "email_reset_password"),#on met le lien pour recevoir un mail
    path("reset_password/activation/<slug:uidb64>/<slug:token>/",views.reset_password,name = "reset_password"),
    
]

templates/general_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Page pour modifier un todo  </h1>
    <h2>Welcome @{{request.user.username}}</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <label for="subject">Sujet</label>
        <input type="text" name="subject" id="">
        <label for="email">Email à envoyer </label>
        <textarea name="email" id="" cols="30" rows="10" placeholder="L'email général à envoyer "></textarea>
        <input type="submit" name="" id="" value="envoyer">
    </form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <h1>Home page</h1>
    {% if user.is_authenticated %}
        <h1>{{user.username}}</h1>
    <a href="{% url 'login:logout' %}">logout</a>
    {% else %}
    <p>please log in </p>
    <a href="{% url 'login:login' %}">login </a>
    <p>or register </p>
    <a href="{% url 'login:register' %}">register</a>
    {% endif %}
</body>
</html>